### ISSUE TITLE
Feature Request: Grab title and text from metatags

### ISSUE THREAD

**Issue by a-haan** [Dabolus/share-menu#5]
Hi

I've now setup the element in my project, since I can't use within an element I was wondering if you can add a feature that will grab the title from the metatag title and grab the text from the metatag description.

I think this will be a good enhancement and make it easier to implement.

Thank you for your great work!

**Comment by Dabolus** [comment]
Hi,

It is actually possible to use this element inside another element (I use this approach inside my own PWA).
Basically, you need a reference to the element, so that you can call the `share` function.

e.g.
```
...imports...
<link rel="import" href="path/to/share-menu.html">
...more imports...

...your element template...
<share-menu id="shareMenu" title="Ohai!" text="Just a test" url="https://www.example.com/"></share-menu>
<paper-button on-click="_share">Share!</paper-button>
...your element class...
_share() {
  // Inside a Polymer Element, you can access an element by id from the 'this.$' object
  this.$.shareMenu.share();
}
...
```

I'm currently using it in this way without any issues. By the way, the description is currently empty by default, so getting the description from the description metatag makes sense to me. The title is already grabbed from the `title` tag, so it should already be ok

**Comment by a-haan** [comment]
Sorry I didn't respond sooner, I've tried your recommendations and it seems to work fine - issues I'm having is the title always seems to be 'undefined' and if I click on a article on my site and then go to another and then click on share, the last article (page)  is shared instead of the current article.  I've not defined url in the component.  I would imagine that obtaining the title would be better from metatags aswell as the description for text, let me know what you think.

**Comment by Dabolus** [comment]
In the latest version, title and description are now both obtained from meta tags

**Comment by a-haan** [comment]
Thank you!

Does the component work with Polymer 2.0 or only 3.0?

**Comment by Dabolus** [comment]
The component has been rewritten as a vanilla component, so it does not depend on any specific library. However, it is currently only published as an ES module, so it is not directly usable with Polymer 2. I might add an UMD version that is usable virtually anywhere, though

**Comment by Dabolus** [comment]
@a-haan FYI now you should be able to use the version 3.x of the element on Polymer 2: https://github.com/Dabolus/share-menu#without-npmyarn

**Comment by a-haan** [comment]
@Dabolus Thank you, tested and all working!

Have you experienced any issues with the URL it grabs not updating on page loads?

**Comment by a-haan** [comment]
got your component working beautifully with this script:

<script>
function shareUpdate() {
document.querySelector('share-menu[id="shareMenu"]').setAttribute('url',  document.location.origin + document.location.pathname + document.location.search);
document.querySelector('share-menu[id="shareMenu"]').setAttribute('title',  document.title);
document.querySelector('share-menu[id="shareMenu"]').setAttribute('text',  'Check out this Article: '+ document.title);
}
</script>
 
Thank you for your great work!

**Comment by Dabolus** [comment]
@a-haan sorry, I completely forgot about this issue since it is closed. By the way, what you are doing is correct. To make sure that title, url and description update on page load I would need to watch those properties, but that's definitely not a good thing to do, so updating them yourself when sharing is definitely a better option.

P.S. If you're using version >=3 of the component, you can also pass those values directly to the share function. The attributes will then automatically be updated.

e.g.
```javascript
shareMenu.share({
  text: `Check out this Article: ${document.title}`,
  title: document.title,
  url: document.location.origin + document.location.pathname + document.location.search,
});
```
