### ISSUE TITLE
How to use with React?

### ISSUE THREAD

**Issue by bitttttten** [Dabolus/share-menu#8]
I am trying to configure this with React and currently, I have the following:

```js
import "share-menu/share-menu.js"

...

return (
	<share-menu
		id="shareMenu"
		title="Ohai!"
		text="Just a test"
		url="https://www.example.com/"
		socials={["telegram", "whatsapp","email", "clipboard", "sms", "twitter"]}
	/>
)
```

Although it does not register the "socials" since React turns it into a string. What's the best way to go about this?

**Comment by Dabolus** [comment]
Hi, the problem with React is that it always sets attributes instead of properties on custom elements. This works well with primitive data types (e.g. strings, numbers, etc.) because primitive properties are automatically reflected to element attributes, but complex data types (i.e. arrays and objects) don't work well because automatically reflecting them would mean to deserialize the attribute to compute its property each time it gets updated and serialize the property to compute its attribute each time it gets updated. Since this process is resource intensive, property to attribute reflection is generally avoided in custom elements. There is [an open RFC](https://github.com/facebook/react/issues/11347) to make it possible to directly use properties in React, so you might be interested in following it.

Until this issue gets fixed, the best way to handle this would be to wrap the custom element into a React component, e.g:

`ShareMenu.jsx`
```jsx
import React from "react";
import "share-menu/share-menu";

export default ({ socials = [], ...params }) => (
  <share-menu
    ref={shareMenu => socials && (shareMenu.socials = socials)}
    {...params}
  />
);
```

`App.jsx`
```jsx
return (
  /* ... */
  <ShareMenu
    title="Ohai!"
    text="Just a test"
    url="https://www.example.com/"
    socials={["telegram", "whatsapp", "email", "clipboard", "sms", "twitter"]}
  />
  /* ... */
);
```

**Comment by bitttttten** [comment]
I see, thanks a lot!

And would you also call it in the same way, by setting the ID? Or could you also use a ref? I guess that is up to the developer really as both would work.

**Comment by bitttttten** [comment]
I also wrapped the `ShareMenu` in `React.lazy` since I was having trouble server rendering share-menu.
